{% set name = "plant-disease-classification" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/abdullahselek/plant-disease-classification/archive/{{ version }}.tar.gz
  sha256: d74f038016d02d5b87426bf606f01d958b914593c4d7dc8376a79143d529b935

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - plant-disease-classification-models ==0.1
    - torch ==1.7
    - torchvision ==0.8
    - numpy ==1.19
    - Pillow ==8.0

test:
  imports:
    - plant-disease-classification

about:
  home: https://github.com/abdullahselek/plant-disease-classification
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A Python module that classifies disease on plants.'
  description: |
    A Python module that classifies disease on plants.
  doc_url: https://plant-disease-classification.abdullahselek.com/
  dev_url: https://github.com/abdullahselek/plant-disease-classification

extra:
  recipe-maintainers:
    - abdullahselek
